### ISSUE TITLE
Moshi Parsing Issue

### ISSUE THREAD

**Issue by tembloroso** [blockfrost/blockfrost-kotlin#1]
Error: 
`com.squareup.moshi.JsonDataException: Expected an int but was NULL at path $.active_epoch`

This can be reproduced by calling (as example): 
`
CardanoApi.accountsApi.getAccountByStakeAddress(stake1uxdegcz0htrg6az954arwx30vq49xspanxcgkumfmjvftugld9mcj)
`

Version:
`implementation 'com.github.blockfrost:blockfrost-kotlin:0.0.3'`

**Comment by ph4r05** [comment]
thanks for report @tembloroso, I will take a look

**Comment by ph4r05** [comment]
@tembloroso v 0.0.4 fixing this issue is released on github.
